# -*- coding: utf-8 -*-
"""Linear regression_visualize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opx8j-CmDl3pSsIHdx6s1-u0ul1NnHGa
"""

import tensorflow as tf
import matplotlib.pyplot as plt

X = [1,2,3]
Y = [1,2,3]

W = tf.placeholder(tf.float32)

hypothesis = X * W
cost = tf.reduce_mean(tf.square(hypothesis - Y))  # linear regression에서 비용함수는 tf.reduce_mean(tf.square(hypothesis - Y))
# Variables for plotting cost function
W_history = []
cost_history = []

sess = tf.Session()
# 그림그리기 위한 W와 cost 변화 값 저장
for i in range(-30,50):
  curr_w = i * 0.1
  curr_cost = sess.run(cost, feed_dict = { W : curr_w})
  
  W_history.append(curr_w)
  cost_history.append(curr_cost)

# show
plt.title('good')       
plt.ylabel('cost')
plt.xlabel('W')
plt.plot(W_history, cost_history)
plt.show()